# Databricks App Configuration
# This file defines how the Databricks Chat Template runs in Databricks Apps

# App metadata
name: "databricks-chat-template"
description: "Production-ready chat application template for Databricks"

# Startup command - install dependencies, wheel, and run app
# Multiple workers enabled for multi-user concurrency
command:
  - "sh"
  - "-c"
  - |
    pip install -r requirements.txt && \
    pip install --upgrade wheels/*.whl && \
    uvicorn src.api.main:app --host 0.0.0.0 --port ${PORT:-8000} --workers 4

# Environment variables
env:
  - name: ENVIRONMENT
    value: "production"
  - name: DATABRICKS_HOST
    valueFrom: "system.databricks_host"  # Injected by Databricks
  - name: DATABRICKS_TOKEN
    valueFrom: "system.databricks_token"  # App service principal token
  - name: LOG_LEVEL
    value: "INFO"
  - name: MLFLOW_TRACKING_URI
    value: "databricks"
  # Lakebase schema configuration
  # PGHOST and PGUSER are auto-set when database resource is attached
  - name: LAKEBASE_SCHEMA
    value: "app_data"

# Note: compute_size is set programmatically during deployment via the Databricks SDK
# Valid values configured in deployment.yaml: MEDIUM, LARGE, LIQUID
